### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fabriziogiordano** [stockmlbot/Client#1]
Hello,
this is not really an issue but a request of support.
I run the Client locally but I can't figure out how to pull the data and run the model.
Is it possible to add in the README.md some more details of which software to run?

Thanks!

**Comment by valamidev** [comment]
Hi,

I managed some update in the Client documentation, but most of the information about TradeCore API you can find in the TradeCore readme:

- https://github.com/stockmlbot/TraderCore/blob/master/README.md

Stockmlbot is designed to run in server environment, so the Client is only used for visualization.
